name: build-macos

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pillow

      - name: Build .app with PyInstaller
        run: |
          pyinstaller --onedir --windowed --icon=icon.icns main.py

      - name: List files in dist folder
        run: ls -la dist/

      - name: Upload .app artifact
        uses: actions/upload-artifact@v3
        with:
          name: MyMacApp
          path: dist/*.app
