name: Build macOS app

on:
  push:
    branches: [ main ]  # adapte selon ta branche

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller openpyxl selenium

    - name: Build app with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=icon.ico main.py

    - name: Upload built app
      uses: actions/upload-artifact@v3
      with:
        name: macos-app
        path: dist/main
